	"(custom patch)",
	"Violin",
	"Guitar",
	"Piano",
	"Flute",
	"Clarinet",
	"Oboe",
	"Trumpet",
	"Organ",
	"Horn",
	"Synthesizer",
	"Harpsichord",
	"Vibraphone",
	"Synthsizer Bass",
	"Acoustic Bass",
	"Electric Guitar",
	"Bass Drum",
	"Snare Drum / Hi-Hat",
	"Tom / Top Cymbal",